spring:
  application:
    name: shadowsocks-backend
  profiles:
    active: prod 
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
